name: Checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set-Up
      run: rustup update stable

    - name: Build
      run: cargo build --verbose
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set-Up
      run: rustup update stable
    
    - name: Run tests
      run: cargo test --verbose
      
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set-Up
        run: rustup update stable

      - name: Run clippy
        run: cargo clippy -- -D warnings
        
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set-Up
        run: rustup update stable

      - name: Run cargofmt
        run: cargo fmt --all -- --check
